# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'React', :path => './ReactComponent/node_modules/react-native', :subspecs => [
     'Core',
  'ART',
  'RCTActionSheet',
  'RCTAdSupport',
  'RCTGeolocation',
  'RCTImage',
  'RCTNetwork',
  'RCTPushNotification',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'RCTLinkingIOS',
  ]
  # Pods for iOSRN

  target 'iOSRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSRNUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
